<?php

namespace Onixcat\Bundle\ViatecParserBundle\Repository;

use Onixcat\Bundle\ViatecParserBundle\Entity\ParserViatecSettings;
use Doctrine\ORM\EntityRepository;

/**
 * ParserViatecSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParserViatecSettingsRepository extends EntityRepository
{

    /**
     * Get login for auth to viatec website
     * @return string
     */
    public function getViatecLogin()
    {
        return $this->getEntityManager()
            ->getRepository(ParserViatecSettings::class)
            ->find(1)
            ->getViatecLogin();
    }

    /**
     * Get password for auth to viatec website
     *
     * @return string
     */
    public function getViatecPassword()
    {
        return $this->getEntityManager()
            ->getRepository(ParserViatecSettings::class)
            ->find(1)
            ->getViatecPassword();
    }
}
